---
title: "My First Markdown"
author: "Jitse"
date: "1-7-2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

download sleep study data
```{r}
library(readr)
sleep<-read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv") 
head(sleep)
cols(
  X1 = col_double(),
  Reaction = col_double(),
  Days = col_integer(),
  Subject = col_double()
)
```

setwd("~/Documents/RSM/Code/Scraping")

```{r}
library(ggplot2)
ggplot(sleep, aes(x=Days, y = Reaction)) + 
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks = seq(0, 8, by = 2)) +
  facet_wrap(~ Subject)
```

```{r}
library(dplyr)
sleep %>%
  group_by(Subject) %>%
  summarise(mean(Reaction))
```


```{r}
sleep %>%
group_by(Subject) %>%
  mutate(mean_centered_reaction = Reaction - mean(Reaction)) %>%
  ggplot(aes(x = Days, y = mean_centered_reaction,
             colour = factor(Subject))) + 
  geom_smooth(show.legend = FALSE, se = FALSE) +
  scale_x_continuous(breaks = seq(0, 8, by = 2))
```









